name: k-gray
favicon: null
layout_spectrum: 0.24216
typography_spectrum: 0.49902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92b1a2'
    - '#2f2900'
    - '#b6c6bb'
    - '#7b7a29'
    - '#51582b'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.612566001014784
purpose: []
