name: k-gray
favicon: null
layout_spectrum: 0.04752037371508777
typography_spectrum: 0.8756280469242483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.542823727009818
  lightness: 0.21629842789843678
  saturation: 0.9181739897467196
  rhythmicContrast: 0.612566001014784
purpose: []
